version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: smartbiz_postgres
    restart: always
    environment:
      POSTGRES_USER: smartbiz
      POSTGRES_PASSWORD: smartbiz
      POSTGRES_DB: smartbiz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
